import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { motion, useScroll, useTransform } from 'framer-motion';
import './index.css';

const photoUrl='/portrait.jpg';
const software=[
{name:'After Effects',years:'6 years',icon:'https://upload.wikimedia.org/wikipedia/commons/c/cb/Adobe_After_Effects_CC_icon.svg',short:'Ae',x:-520},
{name:'Adobe Photoshop',years:'10 years',icon:'https://upload.wikimedia.org/wikipedia/commons/a/af/Adobe_Photoshop_CC_icon.svg',short:'Ps',x:-312},
{name:'Procreate',years:'5 years',customIcon:'procreate',short:'Pr',x:-104},
{name:'Spine 2D',years:'4 years',customIcon:'spine',short:'Sp',x:104},
{name:'Premiere Pro',years:'10 years',icon:'https://upload.wikimedia.org/wikipedia/commons/4/40/Adobe_Premiere_Pro_CC_icon.svg',short:'Pr',x:312},
{name:'Blender',years:'2 years',icon:'https://upload.wikimedia.org/wikipedia/commons/0/0c/Blender_logo_no_text.svg',short:'Bl',x:520},
];
const topSkills=['2D Animation Direction','Motion Design','Art Direction','AI-assisted Creative Workflow','Character Animation','Compositing & Visual Polish','Writing After Effects Scripts with AI','3D Modeling & Simple 3D Animation','Trend Analysis','Storyboarding','Generating Ideas'];
const projects = [
  {
    title: "Cooking Diary: Ramen Shop",
    youtubeId: "zV2lKstW72c",
    href: "https://youtu.be/zV2lKstW72c",
    tags: ["3D Modeling", "3D Animation", "Spine Character Animation"]
  },
  {
    title: "Seekers Notes: Candle Search",
   youtubeId: "1xM5z06LN4g",
    href: "https://youtu.be/1xM5z06LN4g",
    tags: ["Hidden Object", "Spine Character Animation"]
  },
  {
    title: "Chef & Friends: Cutting Steak",
    youtubeId: "XrSs9RZB5c4",
    href: "https://youtube.com/shorts/XrSs9RZB5c4",
    tags: ["Spine Character Animation", "Cooking Simulation"]
  },
  {
    title: "Cooking Diary: Battle of Restaurants",
    youtubeId: "PMw9pCBRLoA",
    href: "https://youtu.be/PMw9pCBRLoA",
    tags: ["Spine 2D", "Motion Design", "Scene Composing"]
  },
  {
    title: "Chef & Friends: Halloween Event Special",
    youtubeId: "jg0TD_foFzo",
    href: "https://youtu.be/jg0TD_foFzo",
    tags: ["Spine 2D", "Character Animation", "Scene Composing"]
  },
  {
    title: "Cooking Diary: Customization Power",
    youtubeId: "zpXgapV80kI",
    href: "https://youtu.be/zpXgapV80kI",
    tags: ["UI Animation", "Spine Character Animation", "Motion Design"]
  },
  {
    title: "Seekers Notes: Possessed by Darkness",
    youtubeId: "WhiieELDaTw",
    href: "https://youtu.be/WhiieELDaTw",
    tags: ["Trailer", "Motion Design", "Visual Storytelling"]
  },
  {
    title: "Unreleased Game Trailer",
    youtubeId: "d8ndITfG0ZM",
    href: "https://youtu.be/d8ndITfG0ZM",
    tags: ["Trailer", "Motion Design"]
  },
  {
    title: "Chef & Friends: Rewards Screen",
    youtubeId: "njWW_FLEh3M",
    href: "https://www.youtube.com/watch?v=njWW_FLEh3M",
    tags: ["Promo Banner", "Spine Character Animation"]
  },
  {
    title: "CD: MERGE OPTIONS",
     youtubeId: "ljQ0IYgtWto",
  href: "https://youtu.be/ljQ0IYgtWto",
    tags: ["Gameplay Creative", "Merge Mechanics"]
  },
  {
    title: "CD:Ice Cream Assemble",
    youtubeId: "X08syxQLk68",
    href: "https://youtu.be/X08syxQLk68",
    tags: ["Gameplay Creative", "Motion Design"]
  },
  {
    title: "CF:Choose the Owner",
   youtubeId: "BwDWaXMRIng",
  href: "https://youtu.be/BwDWaXMRIng",
    tags: ["Gameplay Creative", "Spine Character Animation"]
  },
  {
    title: "CD:Sausage Assembly",
   youtubeId: "FLk4qtvdHPM",
  href: "https://youtu.be/FLk4qtvdHPM",
    tags: ["Gameplay Creative", "Simulation"]
  },
  {
    title: "SN:Missing Girl",
    youtubeId: "4dH3sQDIscY",
    href: "https://youtu.be/4dH3sQDIscY",
    tags: ["Gameplay Creative", "Hidden Object"]
  },
  {
    title: "SN:Dinosaur Eggs",
    youtubeId: "zDgwZ3qmTVw",
    href: "https://youtube.com/shorts/zDgwZ3qmTVw?feature=share",
    tags: ["AI INTRO, Gameplay Creative", "Hidden Object"]
  },
  {
    title: "Cooking Diary: Halloween Storyline",
    youtubeId: "Z6LCAZGzIms",
    href: "https://youtu.be/Z6LCAZGzIms",
    tags: ["Storytelling", "Spine 2D", "Scene Composing"]
  }
];
function clamp01(v){return Math.min(Math.max(v,0),1)}
function InlineSoftwareLogo({type}){if(type==='procreate')return <div className="relative h-full w-full overflow-hidden rounded-[22px] bg-[#242424]"><svg viewBox="0 0 100 100" className="absolute inset-0 h-full w-full"><defs><linearGradient id="procreateA" x1="10" y1="85" x2="90" y2="15"><stop offset="0" stopColor="#fff7a6"/><stop offset=".18" stopColor="#55ef8b"/><stop offset=".36" stopColor="#16b8f2"/><stop offset=".58" stopColor="#ff5ad8"/><stop offset=".78" stopColor="#ff2b5f"/><stop offset="1" stopColor="#8a4dff"/></linearGradient><linearGradient id="procreateLight" x1="18" y1="75" x2="76" y2="38"><stop offset="0" stopColor="#fff9b8"/><stop offset=".5" stopColor="#ffd5c8"/><stop offset="1" stopColor="#ff79d8"/></linearGradient></defs><path d="M12 86 C18 49 42 40 61 32 C78 25 86 14 84 7 C91 29 78 55 47 67 C31 73 19 80 12 86Z" fill="url(#procreateA)"/><path d="M14 78 C27 58 42 52 61 47 C75 43 83 33 84 15 C78 43 54 54 36 61 C26 65 18 71 14 78Z" fill="url(#procreateLight)" opacity=".92"/><path d="M30 70 C45 64 61 64 78 50 C65 69 45 76 24 83 C26 78 28 74 30 70Z" fill="#ff8a00" opacity=".95"/></svg></div>; if(type==='spine')return <div className="relative h-full w-full overflow-hidden rounded-[22px] bg-[#242424]"><svg viewBox="0 0 100 100" className="absolute inset-0 h-full w-full"><path d="M32 10 C42 12 57 10 66 9 C72 8 78 11 78 17 C79 25 72 31 62 31 C51 31 40 28 32 25 C24 22 23 12 32 10Z" fill="#ff4b0b"/><path d="M34 39 C44 41 55 40 64 39 C70 39 75 43 75 50 C75 57 68 62 59 62 C49 62 40 60 33 57 C26 54 26 41 34 39Z" fill="#ff4b0b"/><path d="M43 69 C51 69 58 67 65 66 C70 66 74 69 74 76 C74 82 68 87 59 87 C51 87 45 85 41 82 C36 78 37 70 43 69Z" fill="#ff4b0b"/></svg></div>;return null}
function SoftwareIcon({item,progress,index}){const spread=clamp01(progress*1.15),label=clamp01((progress-.38)*2.8),pos=[-232.5,-139.5,-46.5,46.5,139.5,232.5],startX=pos[index]??item.x*.32,currentX=startX+(item.x-startX)*spread;return <motion.div className="absolute left-1/2 top-1/2 flex -translate-x-1/2 -translate-y-1/2 flex-col items-center" animate={{x:currentX,y:0}} transition={{type:'tween',ease:'linear',duration:.05}}><motion.div className="relative flex h-[88px] w-[88px] items-center justify-center overflow-hidden rounded-[22px] border-[7px] border-black/70 bg-[#111] shadow-[0_16px_40px_rgba(0,0,0,0.22)] before:absolute before:inset-[2px] before:rounded-[16px] before:border-[1.5px] before:border-white/10 before:content-['']" whileHover={{y:-5}}>{item.customIcon?<InlineSoftwareLogo type={item.customIcon}/>:<><img src={item.icon} alt={item.name} className="h-full w-full object-cover" onError={e=>{e.currentTarget.style.display='none';e.currentTarget.nextSibling.style.display='flex'}}/><span className="hidden h-full w-full items-center justify-center text-3xl font-black text-[#f4f1e9]">{item.short}</span></>}</motion.div><motion.div className="pointer-events-none mt-5 w-[170px] text-center" animate={{opacity:label,y:14-label*14}} transition={{duration:.08}}><div className="text-[18px] font-black uppercase leading-[0.92] tracking-[-0.055em]">{item.name}</div><div className="mt-2 font-sans text-[13px] font-semibold uppercase tracking-[0.18em] text-black/75">{item.years}</div></motion.div></motion.div>}

function MobileSoftwareItem({item,index,progress}){const spread=clamp01(progress*1.15),label=clamp01((progress-.32)*2.6),fromX=[76,0,-76,76,0,-76],fromY=[58,58,58,-58,-58,-58],x=fromX[index]*(1-spread),y=fromY[index]*(1-spread);return <motion.div className="flex min-w-0 flex-col items-center justify-start" animate={{x,y,scale:.92+spread*.08,opacity:.35+spread*.65}} transition={{type:'tween',ease:'linear',duration:.05}}><div className="relative flex h-[76px] w-[76px] items-center justify-center overflow-hidden rounded-[19px] border-[6px] border-black/70 bg-[#111] shadow-[0_12px_28px_rgba(0,0,0,0.20)] before:absolute before:inset-[2px] before:rounded-[13px] before:border before:border-white/10 before:content-['']">{item.customIcon?<InlineSoftwareLogo type={item.customIcon}/>:<><img src={item.icon} alt={item.name} className="h-full w-full object-cover" onError={e=>{e.currentTarget.style.display='none';e.currentTarget.nextSibling.style.display='flex'}}/><span className="hidden h-full w-full items-center justify-center text-2xl font-black text-[#f4f1e9]">{item.short}</span></>}</div><motion.div className="pointer-events-none mt-3 w-[105px] text-center" animate={{opacity:label,y:8-label*8}} transition={{duration:.08}}><div className="text-[11px] font-black uppercase leading-[0.95] tracking-[-0.035em]">{item.name}</div><div className="mt-1 font-sans text-[8.5px] font-semibold uppercase tracking-[0.14em] text-black/75">{item.years}</div></motion.div></motion.div>}
function MobileSoftwareGrid({progress}){return <div className="mx-auto grid w-full max-w-[360px] grid-cols-3 gap-x-6 gap-y-8 px-2">{software.map((item,i)=><MobileSoftwareItem key={item.name} item={item} index={i} progress={progress}/>)}</div>}

function TopSkillItem({skill,index,progress}){const total=topSkills.length,start=index/(total+5),duration=.34,reveal=clamp01((progress-start)/duration),eased=reveal*reveal*(3-2*reveal),initialOffset=420+index*90;return <li className="group grid grid-cols-[72px_1fr] items-center gap-5 border-t border-black/25 py-5 md:grid-cols-[110px_1fr] md:py-5" style={{opacity:.08+eased*.92,transform:`translate3d(${initialOffset-eased*initialOffset}px,0,0)`,willChange:'transform, opacity'}}><span className="font-mono text-xs uppercase tracking-[0.35em]" style={{opacity:.2+eased*.8}}>{String(index+1).padStart(2,'0')}</span><span className="text-2xl font-black uppercase leading-[0.9] tracking-[-0.06em] text-black md:text-[3.5rem]">{skill}</span></li>}
function RoleItem({children}){return <div className="flex items-center gap-4"><div className="h-3 w-3 shrink-0 rounded-full bg-black"/><span className="text-[17px] font-bold uppercase tracking-[0.07em] md:text-[1.35rem]">{children}</span></div>}
function Play(){return <div className="absolute left-1/2 top-1/2 flex h-20 w-20 -translate-x-1/2 -translate-y-1/2 items-center justify-center rounded-full border border-white/30 bg-black/50 backdrop-blur-sm transition-transform duration-500 group-hover/video:scale-110"><div className="ml-1 h-0 w-0 border-b-[14px] border-l-[22px] border-t-[14px] border-b-transparent border-l-white border-t-transparent"/></div>}
function GameplayCard({project}){return <div className="group relative block aspect-[16/9] overflow-hidden border border-black bg-black shadow-[8px_8px_0_#111] transition-all duration-500 hover:-translate-y-2"><iframe src={`https://www.youtube.com/embed/${project.youtubeId}`} title="Gameplay video" className="absolute inset-0 h-full w-full" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowFullScreen/><a href={project.href} target="_blank" rel="noreferrer" aria-label="Open gameplay video on YouTube" className="absolute right-3 top-3 z-20 flex h-9 w-9 items-center justify-center rounded-full border border-white/30 bg-black/65 text-white backdrop-blur-sm transition-all duration-300 hover:scale-110 hover:bg-white hover:text-black"><svg viewBox="0 0 24 24" className="h-4 w-4" fill="none" stroke="currentColor" strokeWidth="2.4" strokeLinecap="round" strokeLinejoin="round"><path d="M7 17L17 7"/><path d="M9 7h8v8"/></svg></a></div>}

function ProjectCard({project}){return <article className="group overflow-hidden border border-black bg-[#f4f1e9] shadow-[8px_8px_0_#111] transition-all duration-500 hover:-translate-y-2"><div className="relative aspect-video overflow-hidden bg-black"><iframe src={`https://www.youtube.com/embed/${project.youtubeId}`} title={`${project.title} video`} className="absolute inset-0 h-full w-full" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowFullScreen/><a href={project.href} target="_blank" rel="noreferrer" aria-label={`Open ${project.title} on YouTube`} className="absolute right-3 top-3 z-20 flex h-9 w-9 items-center justify-center rounded-full border border-white/30 bg-black/65 text-white backdrop-blur-sm transition-all duration-300 hover:scale-110 hover:bg-white hover:text-black"><svg viewBox="0 0 24 24" className="h-4 w-4" fill="none" stroke="currentColor" strokeWidth="2.4" strokeLinecap="round" strokeLinejoin="round"><path d="M7 17L17 7"/><path d="M9 7h8v8"/></svg></a></div><div className="p-5"><h3 className="min-h-[3.6rem] text-xl font-black uppercase leading-[0.9] tracking-[-0.055em] md:text-2xl">{project.title}</h3><div className="mt-4 flex flex-wrap gap-2">{project.tags.map(tag=><span key={tag} className="border border-black/25 px-2.5 py-1 font-mono text-[9px] uppercase tracking-[0.18em] text-black/65">{tag}</span>)}</div></div></article>}

function PortfolioCard({project}){const isDark=project.theme==='dark';const card=isDark?'border-black bg-[#111] text-[#f4f1e9] shadow-[10px_10px_0_#f4f1e9]':'border-black bg-[#f4f1e9] text-black shadow-[10px_10px_0_#111]';const badge=isDark?'border-white/20 bg-black/60 text-[#f4f1e9]/80':'border-black/15 bg-[#f4f1e9]/80 text-black/70';const frame=isDark?'border-white/20':'border-black/15';const desc=isDark?'text-[#f4f1e9]/65':'text-black/60';const btn=isDark?'border-[#f4f1e9]/30 text-[#f4f1e9] hover:bg-[#f4f1e9] hover:text-black':'border-black/20 text-black/70 hover:bg-black hover:text-[#f4f1e9]';return <div className={`group relative mx-auto max-w-6xl overflow-hidden border p-4 transition-transform duration-500 hover:-translate-y-1 md:p-5 ${card}`}><div className={`absolute left-6 top-6 z-10 rounded-full border px-4 py-2 font-mono text-[10px] uppercase tracking-[0.28em] backdrop-blur ${badge}`}>{project.number}</div><div className={`relative mx-auto block aspect-video max-w-[92%] overflow-hidden border bg-black ${frame}`}><iframe src={`https://www.youtube.com/embed/${project.youtubeId}`} title={`${project.title} video`} className="absolute inset-0 h-full w-full" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowFullScreen/></div><div className="mt-6 flex flex-col gap-5 md:flex-row md:items-end md:justify-between"><div><h3 className="text-3xl font-black uppercase leading-[0.9] tracking-[-0.06em] md:text-5xl">{project.title}</h3><p className={`mt-4 max-w-3xl text-base font-medium leading-relaxed md:text-lg ${desc}`}>{project.description}</p></div><a href={project.href} target="_blank" rel="noreferrer" className={`inline-flex items-center justify-center border px-5 py-3 font-mono text-xs uppercase tracking-[0.25em] transition-colors ${btn}`}>Open on YouTube</a></div></div>}
function SectionTitle({num,label,title,dark=false}){return <div className={dark?'mt-10 mb-14 border border-black bg-[#111] text-[#f4f1e9] px-8 py-6 shadow-[8px_8px_0_#f4f1e9]':'mt-10 mb-14 border border-black bg-[#f4f1e9] px-8 py-6 shadow-[8px_8px_0_#111]'}><div className={dark?'font-mono text-xs uppercase tracking-[0.35em] text-white/45':'font-mono text-xs uppercase tracking-[0.35em] text-black/45'}>{num}</div><h3 className="mt-4 text-4xl font-black uppercase leading-[0.9] tracking-[-0.06em] md:text-6xl">{title}</h3></div>}
function Site(){const [softwareProgress,setSoftwareProgress]=useState(0),[skillsProgress,setSkillsProgress]=useState(0);const{scrollYProgress}=useScroll();const heroScale=useTransform(scrollYProgress,[0,.25],[1,.86]);const heroY=useTransform(scrollYProgress,[0,.25],[0,-90]);useEffect(()=>{const update=()=>{const section=document.getElementById('software-section');if(section){const r=section.getBoundingClientRect(),s=innerHeight*.82,e=innerHeight*.18;setSoftwareProgress(clamp01((s-r.top)/(s-e)))}const skills=document.getElementById('top-skills-list');if(skills){const r=skills.getBoundingClientRect(),s=innerHeight*.82,e=-r.height*.45;setSkillsProgress(clamp01((s-r.top)/(s-e)))}};update();addEventListener('scroll',update,{passive:true});addEventListener('resize',update);return()=>{removeEventListener('scroll',update);removeEventListener('resize',update)}},[]);return <main className="min-h-screen bg-[#b8b2aa] text-[#111] selection:bg-black selection:text-white"><div className="fixed left-0 top-0 z-50 h-1 w-full bg-black/10"><motion.div className="h-full bg-black" style={{scaleX:scrollYProgress,transformOrigin:'0%'}}/></div>
<section className="relative flex min-h-screen items-center overflow-hidden px-5 py-12 md:px-12"><div className="absolute inset-0 opacity-[0.08] [background-image:linear-gradient(#111_1px,transparent_1px),linear-gradient(90deg,#111_1px,transparent_1px)] [background-size:42px_42px]"/><motion.div style={{scale:heroScale,y:heroY}} className="relative mx-auto grid w-full max-w-7xl gap-6 md:grid-cols-[1.1fr_0.9fr]"><div className="border border-black bg-[#f4f1e9] p-5 shadow-[12px_12px_0_#111] md:p-8"><p className="mb-4 font-mono text-xs uppercase tracking-[0.35em]">Resume / Portfolio / Presentation</p><h1 className="max-w-4xl text-[18vw] font-black uppercase leading-[0.76] tracking-[-0.06em] md:text-[9.6rem]">ALISA<br/>AMIROVA</h1><div className="mt-8 border-t border-black pt-6"><div className="flex flex-col gap-4 md:gap-5"><RoleItem>Direction of 2D Animation Bachelor</RoleItem><RoleItem>Motion Designer Specializing in 2D</RoleItem><RoleItem>AI Specialist</RoleItem></div></div></div><div className="relative border border-black bg-[#111] p-4 shadow-[12px_12px_0_#f4f1e9]"><div className="absolute -left-4 top-6 z-10 -rotate-90 bg-[#f4f1e9] px-3 py-1 font-black uppercase tracking-[-0.05em]">About me</div><div className="grid h-full min-h-[560px] grid-rows-[1fr_auto] gap-4"><div className="overflow-hidden border border-[#f4f1e9]/40 bg-[#2b261f]"><img src={photoUrl} alt="Alisa Amirova portrait" className="h-full w-full object-cover grayscale-[25%] contrast-125 brightness-90"/></div><p className="bg-[#f4f1e9] p-5 text-lg font-medium leading-tight tracking-[-0.04em] md:text-2xl">An artist since childhood with 6+ years of professional experience in GameDev, I combine animation direction, storytelling and visual sensibility to make every project feel like its own little film.</p></div></div></motion.div></section>
<section id="software-section" className="relative min-h-[86vh] overflow-hidden px-5 md:min-h-[78vh] md:px-12"><div className="sticky top-0 flex h-[86vh] items-center justify-center overflow-hidden md:h-[78vh]"><div className="absolute left-5 top-10 z-10 md:left-12"><div className="text-[18vw] font-black uppercase leading-[0.72] tracking-[-0.12em] md:text-[9rem]">SOFTWARE</div><p className="mt-4 max-w-md font-mono text-xs uppercase tracking-widest">Tools I use to bring ideas to life.</p></div><div className="relative mx-auto mt-24 flex h-[420px] w-full max-w-[390px] items-center justify-center md:hidden"><div className="absolute -left-[8%] top-[2%] h-40 w-40 rotate-12 border border-white/45"/><div className="absolute left-[9%] top-[30%] h-20 w-20 -rotate-12 border border-black/25"/><div className="absolute right-[-4%] top-[6%] h-48 w-48 -rotate-[18deg] border border-white/45"/><div className="absolute left-1/2 top-1/2 h-px w-[78%] -translate-x-1/2 bg-black/10"/><MobileSoftwareGrid progress={softwareProgress}/></div><div className="relative mx-auto mt-6 hidden h-[390px] w-full max-w-7xl items-center justify-center md:flex"><div className="absolute -left-[8%] top-[2%] h-48 w-48 rotate-12 border border-white/45"/><div className="absolute left-[11%] top-[28%] h-20 w-20 -rotate-12 border border-black/25"/><div className="absolute right-[-6%] top-[4%] h-56 w-56 -rotate-[18deg] border border-white/45"/><div className="absolute left-1/2 top-1/2 h-px w-[78%] -translate-x-1/2 bg-black/10"/>{software.map((item,i)=><SoftwareIcon key={item.name} item={item} index={i} progress={softwareProgress}/>)}</div></div></section>
<section className="grid min-h-[76vh] place-items-center px-5 py-16 md:-mt-40 md:px-12"><div className="relative w-full max-w-7xl overflow-hidden border border-black bg-[#f4f1e9] p-6 shadow-[12px_12px_0_#111] md:p-10"><div className="relative grid items-center gap-10 md:grid-cols-[1fr_0.82fr]"><div><p className="font-mono text-xs uppercase tracking-[0.35em]">04 / Background</p><h2 className="mt-5 text-[16vw] font-black uppercase leading-[0.75] tracking-[-0.08em] md:text-[8rem]">EDUCATION</h2><div className="mt-10 border-t border-black pt-8"><p className="max-w-3xl text-4xl font-black uppercase leading-[0.9] tracking-[-0.06em] md:text-6xl">VGIK Gerasimov Institute of Cinematography</p><p className="mt-6 max-w-2xl text-xl font-medium leading-tight tracking-[-0.04em] md:text-3xl">Bachelor&apos;s degree in Directing Animation and Computer Graphics</p></div></div><div className="relative mx-auto aspect-square w-full max-w-[420px]"><svg viewBox="0 0 420 420" className="relative h-full w-full" aria-label="minimal cinema camera illustration"><rect x="86" y="158" width="210" height="132" rx="18" fill="#111"/><rect x="110" y="181" width="158" height="84" rx="10" fill="#f4f1e9" opacity="0.12"/><circle cx="138" cy="128" r="52" fill="none" stroke="#111" strokeWidth="18"/><circle cx="238" cy="122" r="42" fill="none" stroke="#111" strokeWidth="14"/><path d="M296 196 L368 158 V290 L296 252 Z" fill="#111"/><path d="M105 318 C154 298 203 337 252 318 C287 305 318 309 352 326" fill="none" stroke="#111" strokeWidth="8" strokeLinecap="round"/></svg></div></div></div></section>
<section id="top-skills-section" className="relative min-h-screen overflow-hidden px-5 py-24 md:px-12 md:py-32"><div className="relative mx-auto max-w-6xl text-center"><p className="font-mono text-xs uppercase tracking-[0.35em] text-black/60">05 / Core strengths</p><h2 className="mt-6 text-[17vw] font-black uppercase leading-[0.75] tracking-[-0.1em] md:text-[8.5rem]">TOP SKILLS</h2><p className="mx-auto mt-6 max-w-xl text-lg font-medium leading-tight tracking-[-0.04em] text-black/65 md:text-2xl">A focused set of creative and technical strengths I bring into every project.</p></div><ul id="top-skills-list" className="relative mx-auto mt-16 max-w-5xl md:mt-20">{topSkills.map((skill,i)=><TopSkillItem key={skill} skill={skill} index={i} progress={skillsProgress}/>)}</ul></section>
<section id="experience-section" className="relative overflow-hidden px-5 py-24 md:px-12 md:py-32"><div className="relative mx-auto max-w-7xl"><div className="flex items-end justify-between gap-8 border-b border-black pb-8"><div><p className="font-mono text-xs uppercase tracking-[0.35em] text-black/60">06 / Career path</p><h2 className="mt-5 text-[18vw] font-black uppercase leading-[0.74] tracking-[-0.1em] md:text-[10rem]">EXPERIENCE</h2></div><p className="max-w-md text-right text-lg font-medium leading-tight tracking-[-0.04em] text-black/65 md:text-2xl">Professional experience across GameDev, advertising and animation production.</p></div><div className="mt-14 space-y-6"><Experience title="Mytona" date="2024 — Present" dark={false}/><Experience title="Green Grey" date="2022 — 2024" dark/><div className="grid gap-6 md:grid-cols-2"><MiniExperience title="AppQuantum" date="2021 — 2022"/><MiniExperience title="Skywaylab" date="2020 — 2022"/></div></div></div></section>
<section id="portfolio-section" className="relative min-h-[100vh] overflow-hidden px-5 py-24 md:px-12 md:py-32"><div className="relative mx-auto max-w-7xl"><div className="flex items-end justify-between gap-8 border-b border-black pb-8"><div><p className="font-mono text-xs uppercase tracking-[0.35em] text-black/60">07 / Selected work</p><h2 className="mt-5 text-[18vw] font-black uppercase leading-[0.74] tracking-[-0.1em] md:text-[10rem]">PORTFOLIO</h2></div><div className="max-w-xl text-right"><p className="text-lg font-medium leading-tight tracking-[-0.04em] text-black/65 md:text-2xl">A selection of motion design, character animation, 3D modeling and animation, gameplay creatives, trailers and visual storytelling.</p></div></div><SectionTitle num="Selected Projects" title="CREATIVE WORK"/><p className="mb-10 max-w-5xl text-base font-normal leading-relaxed tracking-[-0.01em] text-black md:text-xl">Motion design, character animation, 3D modeling and animation, gameplay simulations, trailers and visual storytelling presented together in one unified gallery.</p><div className="grid grid-cols-1 gap-8 md:grid-cols-2 xl:grid-cols-3">{projects.map(p=><ProjectCard key={p.youtubeId} project={p}/>)}</div></div></section>
<section id="old-portfolio-section" className="relative overflow-hidden px-5 pt-8 pb-10 md:px-12 md:pt-12 md:pb-14"><div className="relative mx-auto max-w-7xl"><a href="https://drive.google.com/drive/folders/1eJxQ1n1IL4IleNW6Bv7vhXjcJmW-WHA5?usp=drive_link" target="_blank" rel="noreferrer" className="group flex flex-col gap-5 border border-black bg-[#f4f1e9] px-6 py-6 shadow-[8px_8px_0_#111] transition-all duration-500 hover:-translate-y-1 md:flex-row md:items-center md:justify-between md:px-8"><div><div className="font-mono text-xs uppercase tracking-[0.35em] text-black/45">08 / Archive</div><h3 className="mt-3 text-3xl font-black uppercase leading-[0.9] tracking-[-0.06em] md:text-5xl">OLD PORTFOLIO</h3><p className="mt-3 text-base font-medium tracking-[-0.02em] text-black/60 md:text-lg">Earlier work archive available on Google Drive.</p></div><div className="inline-flex items-center gap-3 border border-black px-5 py-3 font-mono text-xs uppercase tracking-[0.25em] transition-colors group-hover:bg-black group-hover:text-[#f4f1e9]">Open Google Drive →</div></a></div></section>
<section id="languages-contact-section" className="relative overflow-hidden px-5 py-24 md:px-12 md:py-32"><div className="relative mx-auto grid max-w-7xl gap-8 lg:grid-cols-[0.9fr_1.1fr]"><div className="group relative overflow-hidden border border-black bg-[#f4f1e9] p-8 shadow-[10px_10px_0_#111] transition-transform duration-500 hover:-translate-y-1 md:p-10"><div className="absolute bottom-8 right-8 z-10 h-24 w-24 opacity-35 md:h-32 md:w-32"><Globe/></div><p className="font-mono text-xs uppercase tracking-[0.35em] text-black/55">09 / Languages</p><h2 className="mt-5 text-[10vw] font-black uppercase leading-[0.78] tracking-[-0.08em] md:text-[4.8rem] lg:text-[5.2rem]">LANGUAGES</h2><div className="mt-12 space-y-8 pr-0 md:pr-28"><div><h3 className="text-3xl font-black uppercase tracking-[-0.055em] md:text-4xl">English</h3><p className="mt-2 text-lg font-medium tracking-[-0.03em] text-black/60 md:text-xl">FLUENT</p></div><div className="h-px w-full bg-black/20"/><div><h3 className="text-3xl font-black uppercase tracking-[-0.055em] md:text-4xl">Russian</h3><p className="mt-2 text-lg font-medium tracking-[-0.03em] text-black/60 md:text-xl">Native / bilingual proficiency</p></div></div></div><div className="relative overflow-hidden border border-black bg-[#111] p-8 text-[#f4f1e9] shadow-[10px_10px_0_#f4f1e9] md:p-10"><p className="font-mono text-xs uppercase tracking-[0.35em] text-white/45">10 / Get in touch</p><h2 className="mt-5 text-[12vw] font-black uppercase leading-[0.78] tracking-[-0.08em] md:text-[5.8rem]">CONTACT INFO</h2><div className="mt-12 grid gap-5"><Contact href="https://www.linkedin.com/in/alisa-a-b337582ab" label="LinkedIn" value="linkedin.com/in/alisa-a-b337582ab" icon="in"/><Contact href="mailto:aliamiinquiries@gmail.com" label="Email" value="aliamiinquiries@gmail.com" icon="✉"/></div></div></div></section>
</main>}
function Experience({title,date,dark}){return <div className={`group relative overflow-hidden border border-black p-6 shadow-[10px_10px_0_#111] transition-all duration-500 hover:-translate-y-1 md:p-8 ${dark?'bg-[#111] text-[#f4f1e9] shadow-[10px_10px_0_#f4f1e9]':'bg-[#f4f1e9]'}`}><div className="absolute right-6 top-6 font-mono text-xs uppercase tracking-[0.35em] opacity-35">{date}</div><h3 className="text-3xl font-black uppercase tracking-[-0.06em] md:text-5xl">{title}</h3><p className="mt-2 text-xl font-semibold uppercase tracking-[0.04em] opacity-75 md:text-2xl">Motion Designer / 2D Animator</p><p className="mt-6 max-w-4xl text-base font-medium leading-relaxed opacity-65 md:text-lg">Creating cinematic mobile game advertising creatives with strong storytelling, animation rhythm and visual direction.</p></div>}
function MiniExperience({title,date}){return <div className="relative overflow-hidden border border-black bg-[#f4f1e9] p-6 shadow-[10px_10px_0_#111] md:p-8"><div className="font-mono text-xs uppercase tracking-[0.35em] text-black/40">{date}</div><div className="mt-8"><h3 className="text-3xl font-black uppercase tracking-[-0.06em] md:text-4xl">{title}</h3><p className="mt-3 text-lg font-semibold uppercase tracking-[0.04em] text-black/70">Motion Designer / Contract</p></div></div>}
function Globe(){return <svg viewBox="0 0 160 160" className="h-full w-full" aria-label="minimal globe icon"><circle cx="80" cy="80" r="58" fill="none" stroke="#111" strokeWidth="6"/><path d="M22 80 H138" stroke="#111" strokeWidth="4" strokeLinecap="round"/><path d="M80 22 C104 47 104 113 80 138 C56 113 56 47 80 22Z" fill="none" stroke="#111" strokeWidth="4"/><path d="M38 48 C60 58 100 58 122 48" fill="none" stroke="#111" strokeWidth="4" strokeLinecap="round"/><path d="M38 112 C60 102 100 102 122 112" fill="none" stroke="#111" strokeWidth="4" strokeLinecap="round"/></svg>}
function Contact({href,label,value,icon}){return <a href={href} target={href.startsWith('http')?'_blank':undefined} rel="noreferrer" className="group flex items-center gap-5 border border-white/20 bg-white/5 p-5 transition-colors hover:bg-[#f4f1e9] hover:text-black md:p-6"><div className="flex h-14 w-14 shrink-0 items-center justify-center border border-current font-black text-2xl">{icon}</div><div><div className="font-mono text-xs uppercase tracking-[0.3em] opacity-55">{label}</div><div className="mt-2 break-all text-xl font-bold tracking-[-0.04em] md:text-3xl">{value}</div></div></a>}

createRoot(document.getElementById('root')).render(<Site/>);
